version: '3'

services:
  traefik:
    image: traefik:alpine
    logging:
        driver: 'json-file'
        options:
            max-size: '1m'
            max-file: '5'
    networks:
      bridge-frontend:
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/certs
      - //var/run/docker.sock:/var/run/docker.sock

networks:
  bridge-frontend:
    external: true
