version: '3'

services:
  traefik:
    image: traefik:alpine
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/certs
      - //var/run/docker.sock:/var/run/docker.sock

  test:
    image: nginx:alpine
    labels:
      - traefik.frontend.rule=Host:test.local.devel.nz
      - traefik.basic.port=80
